# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='*', max_length=255),
        ),
    ]
