# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('timeout_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='login.users')),
            ],
        ),
    ]
