# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_sessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='user_id',
            new_name='user',
        ),
    ]
